[build-system]
build-backend = "setuptools.build_meta"
requires = [ "setuptools>=62.4.0", "wheel" ]

[project]
authors = [ { email = "git@nertzy.com", name = "Grant Hutchins" } ]
classifiers = [
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Compilers",
  "Topic :: Text Processing :: Linguistic",
  "Typing :: Typed",
]
description = "Bats (Bash Automated Testing System) grammar for tree-sitter, extending tree-sitter-bash."
keywords = [ "incremental", "parsing", "tree-sitter", "bats" ]
license.text = "MIT"
name = "tree-sitter-bats"
readme = "README.md"
requires-python = ">=3.10"
version = "0.1.0"

[project.urls]
Homepage = "https://github.com/nertzy/tree-sitter-bats"

[project.optional-dependencies]
core = [ "tree-sitter~=0.24" ]

[tool.cibuildwheel]
build = "cp310-*"
build-frontend = "build"
test-requires = [ "tree-sitter~=0.24" ]
test-command = "python -m unittest discover --start-directory {project}/bindings/python/tests"
